### PR TITLE
Array support

### PR DESCRIPTION
**Pull request by fhrtms**
Read and write arrays...

### CODE REVIEW

**Comment by reijosirila** [comment]
Can you please add comment how to use it ? 
Thanks !

**Comment by inando** [comment]
An example on how to use it would be nice!

**Comment by fhrtms** [comment]
Declare an array in your PLC:
image

Then you can use it in your handle:
```
var myHandle = {
    symname: 'MAIN.RZUFALLOUT[1]',
    bytelength: ads.LREAL,
    propname: 'value'
};
```
and in your script:
```
client = ads.connect(options, function() {
    this.read(myHandle, function(err, handle) {
        console.log(handle.value);
    });

    this.notify(myHandle);

    this.on('notification', function(handle){
        console.log(handle.value);
    });
});
```

**Comment by reijosirila** [comment]
It works great! Thank you!

**Pull request merged**
